FROM golang:alpine AS builder
WORKDIR /build/
COPY webservice/public-ip .
RUN go mod tidy
RUN go mod download
RUN GOOS=linux GOARCH=amd64 go build -o main ./main.go ./app.go
RUN pwd

FROM alpine
COPY --from=builder /build/main .
CMD ["/main"]