name: Build image manually
on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: true
      service-name:
        description: 'Service name'
        required: true
      tag:
        description: 'Tag name'
        required: true

env:
  REGISTRY: ghcr.io
  REPO_USER: rezkyauliapratama

jobs:
  build-image-and-push:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
          
      - name: Building service
        uses: ./.github/workflows/composite/echo

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2     

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REPO_USER }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/Dockerfile.${{ github.event.inputs.service-name }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.REPO_USER }}/${{ github.event.inputs.service-name }}:${{ github.event.inputs.tag }}
          platforms: linux/amd64

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}